api_platform:
  title: Uber Bagarre API Platform
  description: The API for Uber Bagarre
  version: 1.0.0
  show_webby: false
  formats:
    jsonld: ["application/ld+json"]
  docs_formats:
    jsonld: ["application/ld+json"]
    jsonopenapi: ["application/vnd.openapi+json"]
    html: ["text/html"]
  defaults:
    stateless: true
    pagination_items_per_page: 5 # Par défaut 30, j'ai mis à 5 pour pas avoir besoin de trop de fixtures
    cache_headers:
      vary: ["Content-Type", "Authorization", "Origin"]
    extra_properties:
      standard_put: true
      rfc_7807_compliant_errors: true
  event_listeners_backward_compatibility_layer: false
  keep_legacy_inflector: false
