vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    fighters:
      uri_prefix: /images/fighters
      upload_destination: "%kernel.project_dir%/public/images/fighters"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
